### ISSUE TITLE
How to check progress(download percent) of a task

### ISSUE THREAD

**Issue by shashank090789** [Khang-NT/File-Downloader#4]

**Comment by Khang-NT** [comment]
You can accomplish this with [`TaskReport` ](https://github.com/Khang-NT/File-Downloader/blob/master/filedownloader/src/main/java/io/github/khangnt/downloader/model/TaskReport.java#L28) class.
`TaskReport` is obtained from event listener ([`FileDownloader.registerListener`](https://github.com/Khang-NT/File-Downloader/blob/master/filedownloader/src/main/java/io/github/khangnt/downloader/FileDownloader.java#L179)) or you can get it directly via `FileDownloader.getTaskReport`
